# Generated by Django 5.2 on 2025-04-22 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('benefits', models.TextField()),
                ('status', models.TextField()),
                ('qrCode', models.CharField(max_length=100, unique=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Taxonomy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.TextField()),
                ('genus', models.TextField()),
                ('species', models.TextField()),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxonomy', to='trees.tree')),
            ],
        ),
        migrations.CreateModel(
            name='EcologyHabitat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habitat', models.TextField()),
                ('location', models.TextField()),
                ('climate', models.TextField()),
                ('tree', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ecology', to='trees.tree')),
            ],
        ),
        migrations.CreateModel(
            name='TreeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelFile', models.FileField(upload_to='treeModels/')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('fileFormat', models.CharField(max_length=50)),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='trees.tree')),
            ],
        ),
        migrations.CreateModel(
            name='TreeNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nativeName', models.CharField(max_length=100)),
                ('scientificName', models.CharField(max_length=100)),
                ('tree', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='trees.tree')),
            ],
        ),
        migrations.CreateModel(
            name='TreePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='treePhotos/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('isPrimary', models.BooleanField(default=False)),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='trees.tree')),
            ],
        ),
    ]
