# Generated by Django 5.2 on 2025-04-22 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxonomy',
            name='tree',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='taxonomy', to='trees.tree'),
        ),
    ]
