# Generated by Django 5.2 on 2025-04-24 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0002_alter_taxonomy_tree'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tree',
            old_name='benefits',
            new_name='uses',
        ),
        migrations.RemoveField(
            model_name='tree',
            name='status',
        ),
        migrations.RemoveField(
            model_name='treenames',
            name='name',
        ),
        migrations.AddField(
            model_name='treenames',
            name='otherNames',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='EcologicalBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habitatType', models.TextField()),
                ('nativeLocation', models.TextField()),
                ('system', models.TextField()),
                ('climate', models.TextField()),
                ('endemicity', models.TextField()),
                ('tree', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ecology', to='trees.tree')),
            ],
        ),
        migrations.DeleteModel(
            name='EcologyHabitat',
        ),
    ]
